name: install npm packages
description: Installs npm packages and manages it's cache

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Cache setup for node modules
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ./node_modules
          ./packages/**/node_modules
        key: ${{ runner.os }}-blade-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages if cache miss
      run: yarn install --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Run postinstall script
      run: yarn postinstall
      shell: bash
      if: steps.cache.outputs.cache-hit == 'true'
