import React from 'react';
import { Checkbox } from './Checkbox';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=71951-34708&m=dev',
  {
    props: {
      helpText: figma.boolean('showHelpText'),
      children: figma.string('label'),
      size: figma.enum('size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large',
      }),
      isDisabled: figma.boolean('isDisabled'),
      isChecked: figma.boolean('isChecked'),
      isIntermediate: figma.boolean('isIntermediate'),
      validationState: figma.enum('validationState', {
        Error: 'error',
      }),
      errorText: figma.boolean('errorText'),
    },

    example: ({ children, errorText, helpText, ...props }) => (
      <Checkbox
        {...props}
        errorText={errorText} // Add error text here
        helpText={helpText} // Add help text here
      >
        {children}
      </Checkbox>
    ),
  },
);
