/**
 * Extracts Blade's icon set (packages/blade/src/components/Icons) into
 * `@razorpay/blade-svelte/icons`: one currentColor SVG per glyph, the
 * codepoint lockfile, the exports (each icon is its SVG file) and the name
 * union. Never builds a font: apps do, with `bladeIconFontPlugin` (Vite or
 * webpack), from the icons they import.
 *
 * Usage (from packages/blade-svelte): node scripts/icon-svgs/extract-blade.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const REACT_ICONS = path.resolve(here, '../../../blade/src/components/Icons');
const OUT = path.resolve(here, '../../src-cx/icons');
const SVG_OUT = path.join(OUT, 'svg');
const LOCKFILE = path.join(OUT, 'codepoints.json');

/** Blade's own codepoint block; consumers' custom glyphs start at U+F000. */
const FIRST_CODE = 0xe000;
const LAST_CODE = 0xefff;

/**
 * A font fills shapes; it cannot draw a stroke. These are Blade's
 * stroke-drawn icons, left out until they are outlined at the source.
 */
const STROKED = new Set(['BluetoothIcon', 'ScissorsIcon']);

/** `ArrowRightIcon` → `arrow-right`, `CheckCircle2Icon` → `check-circle-2`. */
export const toKebab = (component) =>
  component
    .replace(/Icon$/, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-zA-Z])([0-9])/g, '$1-$2')
    .toLowerCase();

const ATTRIBUTES = {
  d: 'd',
  fillRule: 'fill-rule',
  clipRule: 'clip-rule',
  cx: 'cx',
  cy: 'cy',
  r: 'r',
  x: 'x',
  y: 'y',
  width: 'width',
  height: 'height',
  rx: 'rx',
  ry: 'ry',
  transform: 'transform',
};

/**
 * The JSX of one icon → SVG markup. Shapes keep their geometry; colour is
 * always currentColor. Clip paths only ever clip to the 24px box, so they and
 * their groups are flattened away.
 */
export function jsxToSvg(source, component) {
  const body = /<Svg\b[^>]*>([\s\S]*?)<\/Svg>/.exec(source)?.[1];
  if (!body) throw new Error(`${component}: no <Svg> element`);
  const withoutDefs = body.replace(/<Defs>[\s\S]*?<\/Defs>/g, '');
  const shapes = [...withoutDefs.matchAll(/<(Path|Circle|Rect)\b([\s\S]*?)\/>/g)].map(
    ([, tag, attributes]) => {
      const pairs = [...attributes.matchAll(/(\w+)=(?:"([^"]*)"|\{([^}]*)\})/g)]
        .filter(([, name]) => name in ATTRIBUTES)
        .map(([, name, value]) => `${ATTRIBUTES[name]}="${value}"`);
      return `<${tag.toLowerCase()} ${pairs.join(' ')}/>`;
    },
  );
  if (shapes.length === 0) throw new Error(`${component}: no shapes`);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">${shapes.join('')}</svg>\n`;
}

/**
 * Keeps every name's code; appends new names in sorted order after the
 * highest code ever handed out; retires removed names so their codes are
 * never reused.
 */
export function updateLockfile(previous, names) {
  const glyphs = { ...previous.glyphs };
  const retired = { ...previous.retired };
  for (const name of Object.keys(glyphs)) {
    if (!names.includes(name)) {
      retired[name] = glyphs[name];
      delete glyphs[name];
    }
  }
  const used = [...Object.values(glyphs), ...Object.values(retired)];
  let next = used.length ? Math.max(...used) + 1 : FIRST_CODE;
  for (const name of [...names].sort()) {
    if (name in glyphs) continue;
    if (name in retired) {
      // Back after a removal: it gets its old code again.
      glyphs[name] = retired[name];
      delete retired[name];
      continue;
    }
    if (next > LAST_CODE) throw new Error('Blade codepoint block U+E000–U+EFFF is full');
    glyphs[name] = next;
    next += 1;
  }
  const sorted = (record) =>
    Object.fromEntries(Object.entries(record).sort(([a], [b]) => a.localeCompare(b)));
  return { glyphs: sorted(glyphs), retired: sorted(retired) };
}

/** `components` maps each glyph name to its Blade component name, the export's name. */
function writeTokens(lock, components) {
  const header = '// Generated by scripts/icon-svgs/extract-blade.mjs: do not edit.\n';
  const names = Object.keys(lock.glyphs);
  // Each icon is its SVG file: a URL in any bundler, a font glyph once a
  // bladeIconFontPlugin (Vite or webpack) is in the build. Plain JS, so the
  // barrel needs no TypeScript tooling; the types sit beside it.
  fs.writeFileSync(
    path.join(OUT, 'glyphs.js'),
    `${header}${names.map((name) => `export { default as ${components[name]} } from './svg/${name}.svg';`).join('\n')}\n`,
  );
  fs.writeFileSync(
    path.join(OUT, 'glyphs.d.ts'),
    `${header}import type { IconSource } from '../runes/icon/source';\n\n${names
      .map((name) => `export declare const ${components[name]}: IconSource;`)
      .join('\n')}\n`,
  );
  fs.writeFileSync(
    path.join(OUT, 'names.ts'),
    `${header}/** Every predefined glyph, by its SVG's file name. */\nexport type BladeIconName =\n${names.map((name) => `  | '${name}'`).join('\n')};\n`,
  );
}

function main() {
  const components = fs
    .readdirSync(REACT_ICONS)
    .filter((entry) => /Icon$/.test(entry) && !STROKED.has(entry))
    .filter((entry) => fs.existsSync(path.join(REACT_ICONS, entry, `${entry}.tsx`)));

  fs.rmSync(SVG_OUT, { recursive: true, force: true });
  fs.mkdirSync(SVG_OUT, { recursive: true });
  const byName = {};
  for (const component of components) {
    const source = fs.readFileSync(path.join(REACT_ICONS, component, `${component}.tsx`), 'utf8');
    const name = toKebab(component);
    if (name in byName) throw new Error(`${component} and ${byName[name]} both become "${name}"`);
    byName[name] = component;
    fs.writeFileSync(path.join(SVG_OUT, `${name}.svg`), jsxToSvg(source, component));
  }
  const names = Object.keys(byName);

  const previous = fs.existsSync(LOCKFILE)
    ? JSON.parse(fs.readFileSync(LOCKFILE, 'utf8'))
    : { glyphs: {}, retired: {} };
  const lock = updateLockfile(previous, names);
  fs.writeFileSync(LOCKFILE, `${JSON.stringify(lock, null, 2)}\n`);
  writeTokens(lock, byName);
  console.log(`extracted ${names.length} glyphs (skipped stroked: ${[...STROKED].join(', ')})`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
