import React from 'react';
import figma from '@figma/code-connect';
import { Link } from '../Link';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */
figma.connect(
  Link,
  'https://www.figma.com/design/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=59519-143300&m=dev',
  {
    props: {
      icon: figma.instance('icon'),
      // TODO: Figure out how to handle iconPosition
      children: figma.string('label'),
      variant: figma.enum('type', {
        Anchor: 'anchor',
        Action: 'button',
      }),
      color: figma.enum('color', {
        Primary: 'primary',
        White: 'white',
        Neutral: 'neutral',
        Negative: 'negative',
        Positive: 'positive',
      }),
      isDisabled: figma.boolean('isDisabled'),
      size: figma.enum('size', {
        Large: 'large',
        Medium: 'medium',
        Small: 'small',
        XSmall: 'xsmall',
      }),
    },
    // @ts-expect-error ignore this line
    example: ({ children, ...props }) => <Link {...props}>{children}</Link>,
  },
);
