version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    # disallow version update PRs, security updates have a separate limit configured from settings UI
    open-pull-requests-limit: 0
    schedule:
      interval: daily
      time: '04:00'
      timezone: Asia/Calcutta
