import type { CSSObject } from 'styled-components';
import type { DotNotationSpacingStringToken } from '~src/_helpers/types';
import type { Border } from '~tokens/global';

export type BoxProps = {
  display?: CSSObject['display'];
  flex?: CSSObject['flex'];
  flexWrap?: CSSObject['flexWrap'];
  flexDirection?: CSSObject['flexDirection'];
  flexGrow?: CSSObject['flexGrow'];
  alignItems?: CSSObject['alignItems'];
  alignContent?: CSSObject['alignContent'];
  justifyContent?: CSSObject['justifyContent'];
  alignSelf?: CSSObject['alignSelf'];
  overflow?: CSSObject['overflow'];
  position?: CSSObject['position'];
  top?: CSSObject['top'];
  right?: CSSObject['right'];
  bottom?: CSSObject['bottom'];
  left?: CSSObject['left'];
  paddingTop?: DotNotationSpacingStringToken | 'auto';
  paddingBottom?: DotNotationSpacingStringToken | 'auto';
  paddingLeft?: DotNotationSpacingStringToken | 'auto';
  paddingRight?: DotNotationSpacingStringToken | 'auto';
  marginTop?: DotNotationSpacingStringToken | 'auto' | number;
  marginBottom?: DotNotationSpacingStringToken | 'auto' | number;
  marginLeft?: DotNotationSpacingStringToken | 'auto' | number;
  marginRight?: DotNotationSpacingStringToken | 'auto' | number;
  borderRadius?: keyof Border['radius'] | number;
  width?: CSSObject['width'];
  height?: CSSObject['height'];
  gap?: DotNotationSpacingStringToken | 'auto' | number;
  minHeight?: number;
  minWidth?: number;
  maxHeight?: number;
  maxWidth?: number;
  className?: string;
  transform?: CSSObject['transform'];
  background?: CSSObject['background'];
  zIndex?: CSSObject['zIndex'];
};
