// @ts-expect-error - CSS modules may not have type definitions in build
import styles from './segmentedControl.module.css';

export const getSegmentedControlTemplateClasses = (): Record<string, string> => ({
  container: styles.container,
  containerSizeSmall: styles.containerSizeSmall,
  containerSizeMedium: styles.containerSizeMedium,
  containerSizeLarge: styles.containerSizeLarge,
  fieldWrapperTop: styles.fieldWrapperTop,
  fieldWrapperLeft: styles.fieldWrapperLeft,
  fieldContent: styles.fieldContent,
  labelTop: styles.labelTop,
  labelLeft: styles.labelLeft,
  hintText: styles.hintText,
  hintTextSmall: styles.hintTextSmall,
  hintTextMedium: styles.hintTextMedium,
  hintTextLarge: styles.hintTextLarge,
  helpText: styles.helpText,
  errorText: styles.errorText,
  item: styles.item,
  itemSelected: styles.itemSelected,
  itemSizeSmall: styles.itemSizeSmall,
  itemSizeMedium: styles.itemSizeMedium,
  itemSizeLarge: styles.itemSizeLarge,
  itemText: styles.itemText,
  itemTextSizeSmall: styles.itemTextSizeSmall,
  itemTextSizeMedium: styles.itemTextSizeMedium,
  itemTextSizeLarge: styles.itemTextSizeLarge,
  itemTextNormal: styles.itemTextNormal,
  itemTextMuted: styles.itemTextMuted,
  itemTextDisabled: styles.itemTextDisabled,
  indicator: styles.indicator,
  indicatorDisabled: styles.indicatorDisabled,
  indicatorAnimating: styles.indicatorAnimating,
  indicatorInstant: styles.indicatorInstant,
  indicatorRadiusSmall: styles.indicatorRadiusSmall,
  indicatorRadiusMediumToken: styles.indicatorRadiusMediumToken,
});
