const icons = {
  arrowDown: require('./ArrowDown').default,
  arrowLeft: require('./ArrowLeft').default,
  arrowRight: require('./ArrowRight').default,
  arrowUp: require('./ArrowUp').default,
  briefcase: require('./Briefcase').default,
  check: require('./Check').default,
  checkboxFilled: require('./CheckboxFilled').default,
  checkboxOutlined: require('./CheckboxOutlined').default,
  chevronDown: require('./ChevronDown').default,
  chevronLeft: require('./ChevronLeft').default,
  chevronRight: require('./ChevronRight').default,
  chevronUp: require('./ChevronUp').default,
  clipboard: require('./Clipboard').default,
  close: require('./Close').default,
  copy: require('./Copy').default,
  failure: require('./Failure').default,
  feather: require('./Feather').default,
  gear: require('./Gear').default,
  info: require('./Info').default,
  invoice: require('./Invoice').default,
  lifeBuoy: require('./LifeBuoy').default,
  mail: require('./Mail').default,
  maximize: require('./Maximize').default,
  minimize: require('./Minimize').default,
  moreVertical: require('./MoreVertical').default,
  paymentLink: require('./PaymentLink').default,
  paymentCapture: require('./PaymentCapture').default,
  paymentGateway: require('./PaymentGateway').default,
  paymentPage: require('./PaymentPage').default,
  phone: require('./Phone').default,
  power: require('./Power').default,
  refund: require('./Refund').default,
  search: require('./Search').default,
  smartCollect: require('./SmartCollect').default,
  subscription: require('./Subscription').default,
  success: require('./Success').default,
  trash: require('./Trash').default,
  wiFiOn: require('./WiFiOn').default,
  wiFiOff: require('./WiFiOff').default,
};

export default icons;
