const icons = {
  arrowDown: require('./ArrowDown').default,
  arrowLeft: require('./ArrowLeft').default,
  arrowRight: require('./ArrowRight').default,
  arrowUp: require('./ArrowUp').default,
  check: require('./Check').default,
  checkboxFilled: require('./CheckboxFilled').default,
  checkboxOutlined: require('./CheckboxOutlined').default,
  chevronDown: require('./ChevronDown').default,
  chevronLeft: require('./ChevronLeft').default,
  chevronRight: require('./ChevronRight').default,
  chevronUp: require('./ChevronUp').default,
  clipboard: require('./Clipboard').default,
  close: require('./Close').default,
  copy: require('./Copy').default,
  failure: require('./Failure').default,
  feather: require('./Feather').default,
  info: require('./Info').default,
  invoice: require('./Invoice').default,
  lifeBuoy: require('./LifeBuoy').default,
  maximize: require('./Maximize').default,
  minimize: require('./Minimize').default,
  moreVertical: require('./MoreVertical').default,
  paymentLink: require('./PaymentLink').default,
  paymentCapture: require('./PaymentCapture').default,
  paymentGateway: require('./PaymentGateway').default,
  paymentPage: require('./PaymentPage').default,
  search: require('./Search').default,
  settings: require('./Settings').default,
  smartCollect: require('./SmartCollect').default,
  subscription: require('./Subscription').default,
  success: require('./Success').default,
};

export default icons;
