import React from 'react';
import { Button } from '../Button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  'https://www.figma.com/design/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=58628-55194&m=dev',
  {
    props: {
      icon: figma.instance('icon'),
      // TODO: Figure out how to handle iconPosition
      // trailingIcon: figma.boolean('↩ trailingIcon'),
      // leadingIcon: figma.boolean('↪ leadingIcon'),
      children: figma.string('label'),
      variant: figma.enum('variant', {
        Primary: 'primary',
        Secondary: 'secondary',
        Tertiary: 'tertiary',
      }),
      color: figma.enum('color', {
        Primary: 'primary',
        White: 'white',
        Positive: 'positive',
        Negative: 'negative',
      }),
      isDisabled: figma.boolean('isDisabled'),
      isLoading: figma.boolean('isLoading'),
      size: figma.enum('size', {
        Large: 'large',
        Medium: 'medium',
        Small: 'small',
        XSmall: 'xsmall',
      }),
      isFullWidth: figma.boolean('isFullWidth'),
    },
    example: ({ children, ...props }) => <Button {...props}>{children}</Button>,
  },
);
