import React from 'react';
import figma from '@figma/code-connect';
import { Button } from './';
//import type { IconComponent } from '~components/Icons';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// Check for dropdown & card components.
figma.connect(
  Button,
  'https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=58628-55194&mode=dev',
  {
    props: {
      icon: figma.instance('icon'),
      iconTrailing: figma.instance('iconTrailing'),
      iconLeading: figma.instance('iconLeading'),
      label: figma.string('label'),
      trailingIcon: figma.boolean('↩ trailingIcon'),
      leadingIcon: figma.boolean('↪ leadingIcon'),
      variant: figma.enum('variant', {
        Primary: 'primary',
        Secondary: 'secondary',
        Tertiary: 'tertiary',
      }),
      color: figma.enum('color', {
        Primary: 'primary',
        White: 'white',
        Positive: 'positive',
        Negative: 'negative',
      }),
      state: figma.enum('state', {
        Default: 'default',
        Hover: 'hover',
        Focus: 'focus',
      }),
      isDisabled: figma.boolean('isDisabled'),
      isLoading: figma.boolean('isLoading'),
      size: figma.enum('size', {
        Large: 'large',
        Medium: 'medium',
        Small: 'small',
        XSmall: 'xsmall',
      }),
      isFullWidth: figma.boolean('isFullWidth'),
      iconOnly: figma.boolean('iconOnly'),
    },
    example: ({ icon, variant, color, isDisabled, isLoading, size, isFullWidth, label }) => (
      <Button
        icon={icon}
        variant={variant}
        color={color}
        isDisabled={isDisabled}
        isLoading={isLoading}
        size={size}
        isFullWidth={isFullWidth}
      >
        {label}
      </Button>
    ),
  },
);
