export type { Border } from './border';
export { border } from './border';
export type { Breakpoints } from './breakpoints';
export { breakpoints } from './breakpoints';
export type { Color } from './colors';
export { colors } from './colors';
export type { Opacity } from './opacity';
export { opacity } from './opacity';
export type { Typography, TypographyWithPlatforms } from './typography';
export { typography } from './typography';
export type { Spacing } from './spacing';
export { spacing } from './spacing';
export type { Motion } from './motion';
export * from './motion';
export type { Size } from './size';
export { size } from './size';
export type { Elevation, ElevationWithColorModes } from './elevation';
export * from './elevation';
