export const MetaConstants = {
  Alert: 'alert',
  Badge: 'badge',
  Button: 'button',
  Checkbox: 'checkbox',
  CheckboxGroup: 'checkbox-group',
  Code: 'code',
  Component: 'blade-component',
  Counter: 'counter',
  Icon: 'icon',
  IconButton: 'icon-button',
  Indicator: 'indicator',
  Link: 'link',
  OTPInput: 'otp-input',
  Radio: 'radio',
  RadioGroup: 'radio-group',
  SkipNav: 'skipnav',
  Spinner: 'spinner',
} as const;
