export const MetaConstants = {
  Alert: 'alert',
  Badge: 'badge',
  Button: 'button',
  Checkbox: 'checkbox',
  CheckboxGroup: 'checkbox-group',
  Code: 'code',
  Component: 'blade-component',
  Counter: 'counter',
  Icon: 'icon',
  IconButton: 'icon-button',
  Indicator: 'indicator',
  Link: 'link',
  List: 'list',
  ListItem: 'list-item',
  OTPInput: 'otp-input',
  ProgressBar: 'progress-bar',
  Radio: 'radio',
  RadioGroup: 'radio-group',
  SkipNav: 'skipnav',
  Spinner: 'spinner',
  Card: 'card',
  CardBody: 'card-body',
  CardHeader: 'card-header',
  CardFooter: 'card-footer',
} as const;
