export const accessibilityMap = {
  accessibilityActiveDescendant: 'aria-activedescendant',
  accessibilityAtomic: 'aria-atomic',
  accessibilityAutoComplete: 'aria-autocomplete',
  accessibilityBusy: 'aria-busy',
  accessibilityChecked: 'aria-checked',
  accessibilityColumnCount: 'aria-colcount',
  accessibilityColumnIndex: 'aria-colindex',
  accessibilityColumnSpan: 'aria-colspan',
  accessibilityControls: 'aria-controls',
  accessibilityDescribedBy: 'aria-describedby',
  accessibilityDetails: 'aria-details',
  accessibilityDisabled: 'aria-disabled',
  accessibilityErrorMessage: 'aria-errormessage',
  accessibilityExpanded: 'aria-expanded',
  accessibilityFlowTo: 'aria-flowto',
  accessibilityHasPopup: 'aria-haspopup',
  accessibilityHidden: 'aria-hidden',
  accessibilityInvalid: 'aria-invalid',
  accessibilityKeyShortcuts: 'aria-keyshortcuts',
  accessibilityLabel: 'aria-label',
  accessibilityLabelledBy: 'aria-labelledby',
  accessibilityLiveRegion: 'aria-live',
  accessibilityModal: 'aria-modal',
  accessibilityMultiline: 'aria-multiline',
  accessibilityMultiSelectable: 'aria-multiselectable',
  accessibilityOrientation: 'aria-orientation',
  accessibilityOwns: 'aria-owns',
  accessibilityPlaceholder: 'aria-placeholder',
  accessibilityPosInSet: 'aria-posinset',
  accessibilityPressed: 'aria-pressed',
  accessibilityReadOnly: 'aria-readonly',
  accessibilityRequired: 'aria-required',
  accessibilityRole: 'role',
  accessibilityRoleDescription: 'aria-roledescription',
  accessibilityRowCount: 'aria-rowcount',
  accessibilityRowIndex: 'aria-rowindex',
  accessibilityRowSpan: 'aria-rowspan',
  accessibilitySelected: 'aria-selected',
  accessibilitySetSize: 'aria-setsize',
  accessibilitySort: 'aria-sort',
  accessibilityValueMax: 'aria-valuemax',
  accessibilityValueMin: 'aria-valuemin',
  accessibilityValueNow: 'aria-valuenow',
  accessibilityValueText: 'aria-valuetext',
};

export const supportedRolesInNative = [
  'adjustable',
  'alert',
  'button',
  'checkbox',
  'combobox',
  'header',
  'image',
  'imagebutton',
  'keyboardkey',
  'link',
  'menu',
  'menubar',
  'menuitem',
  'none',
  'progressbar',
  'radio',
  'radiogroup',
  'scrollbar',
  'search',
  'spinbutton',
  'summary',
  'switch',
  'tab',
  'tablist',
  'text',
  'timer',
  'togglebutton',
  'toolbar',
];

export type AccessibilityMap = Partial<typeof accessibilityMap>;
