import React from 'react';
import { Badge } from './Badge';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  'https://www.figma.com/design/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=8110-469&m=dev',
  {
    props: {
      children: figma.string('label'),
      showLeadingIcon: figma.boolean('showLeadingIcon'),
      leadingIcon: figma.instance('leadingIcon'),
      color: figma.enum('color', {
        Positive: 'positive',
        Negative: 'negative',
        Notice: 'notice',
        Information: 'information',
        Neutral: 'neutral',
        Primary: 'primary',
      }),
      size: figma.enum('size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large',
      }),
      emphasis: figma.enum('emphasis', {
        Subtle: 'subtle',
        Intense: 'intense',
      }),
    },
    example: ({ children, ...props }) => <Badge {...props}>{children}</Badge>,
  },
);
