import React from "react"
import { CardHeader } from "./CardHeader"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardHeader,
  "https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=72069-196853&mode=dev",
  {
    props: {
      showTrailingItem: figma.boolean("showTrailingItem"),
      showLeadingIcon: figma.boolean("showLeading_Icon"),
      showCounter: figma.boolean("showCounter"),
      leadingIcon: figma.instance("leadingIcon"),
      showDivider: figma.boolean("showDivider"),
      showSubtitle: figma.boolean("showSubtitle"),
      screenSize: figma.enum("screenSize", {
        Desktop: "desktop",
        Mobile: "mobile",
      }),
    },
    example: (props) => <CardHeader />,
  },
)
