/**
 * Blade Design System — Tailwind v3 preset (GENERATED — do not edit by hand).
 *
 * Regenerate with `yarn generate:tailwind-preset` (source: `tailwind/generatePreset.ts`).
 * A CI drift test (`tailwind/__tests__/preset-drift.test.ts`) fails if this file is edited or stale.
 *
 * Every value here resolves to a `var(--…)` defined by `@razorpay/blade-core/tokens/theme.css`
 * (light `:root` + `[data-blade-color-scheme='dark']`) and by BladeProvider's runtime brand
 * overrides — so a consumer's runtime dark/brand theming flows through unchanged.
 *
 * Usage (any Tailwind v3 app):
 *   // tailwind.config.js
 *   module.exports = {
 *     presets: [require('@razorpay/blade-core/tailwind/preset')],
 *     content: [
 *       './src/**\/*.{js,ts,svelte}',
 *       './node_modules/@razorpay/blade-svelte/dist/**\/*.js',
 *       './node_modules/@razorpay/blade-core/dist/**\/*.js',
 *     ],
 *   };
 */
const plugin = require('./plugin.cjs');
const { bladeSafelist } = require('./safelist.cjs');

/** @type {import('tailwindcss').Config} */
module.exports = {
  // A library must never inject Tailwind's global reset into a consumer's page.
  corePlugins: { preflight: false },
  // Dark mode keys off the attribute BladeProvider sets (not `.dark` or `prefers-color-scheme`).
  darkMode: ['selector', "[data-blade-color-scheme='dark']"],
  safelist: bladeSafelist,
  theme: {
    extend: {
      colors: {
        'surface-background-gray-subtle': 'var(--surface-background-gray-subtle)',
        'surface-background-gray-moderate': 'var(--surface-background-gray-moderate)',
        'surface-background-gray-intense': 'var(--surface-background-gray-intense)',
        'surface-background-primary-faint': 'var(--surface-background-primary-faint)',
        'surface-background-primary-subtle': 'var(--surface-background-primary-subtle)',
        'surface-background-primary-moderate': 'var(--surface-background-primary-moderate)',
        'surface-background-primary-intense': 'var(--surface-background-primary-intense)',
        'surface-background-primary-strong': 'var(--surface-background-primary-strong)',
        'surface-background-sea-subtle': 'var(--surface-background-sea-subtle)',
        'surface-background-sea-intense': 'var(--surface-background-sea-intense)',
        'surface-background-cloud-subtle': 'var(--surface-background-cloud-subtle)',
        'surface-background-cloud-intense': 'var(--surface-background-cloud-intense)',
        'surface-background-accent-intense': 'var(--surface-background-accent-intense)',
        'surface-border-gray-normal': 'var(--surface-border-gray-normal)',
        'surface-border-gray-subtle': 'var(--surface-border-gray-subtle)',
        'surface-border-gray-muted': 'var(--surface-border-gray-muted)',
        'surface-border-primary-normal': 'var(--surface-border-primary-normal)',
        'surface-border-primary-muted': 'var(--surface-border-primary-muted)',
        'surface-text-gray-normal': 'var(--surface-text-gray-normal)',
        'surface-text-gray-subtle': 'var(--surface-text-gray-subtle)',
        'surface-text-gray-muted': 'var(--surface-text-gray-muted)',
        'surface-text-gray-disabled': 'var(--surface-text-gray-disabled)',
        'surface-text-primary-normal': 'var(--surface-text-primary-normal)',
        'surface-text-on-sea-subtle': 'var(--surface-text-on-sea-subtle)',
        'surface-text-on-sea-intense': 'var(--surface-text-on-sea-intense)',
        'surface-text-on-cloud-subtle': 'var(--surface-text-on-cloud-subtle)',
        'surface-text-on-cloud-intense': 'var(--surface-text-on-cloud-intense)',
        'surface-text-static-white-normal': 'var(--surface-text-static-white-normal)',
        'surface-text-static-white-subtle': 'var(--surface-text-static-white-subtle)',
        'surface-text-static-white-muted': 'var(--surface-text-static-white-muted)',
        'surface-text-static-white-disabled': 'var(--surface-text-static-white-disabled)',
        'surface-text-static-black-normal': 'var(--surface-text-static-black-normal)',
        'surface-text-static-black-subtle': 'var(--surface-text-static-black-subtle)',
        'surface-text-static-black-muted': 'var(--surface-text-static-black-muted)',
        'surface-text-static-black-disabled': 'var(--surface-text-static-black-disabled)',
        'surface-icon-gray-normal': 'var(--surface-icon-gray-normal)',
        'surface-icon-gray-subtle': 'var(--surface-icon-gray-subtle)',
        'surface-icon-gray-muted': 'var(--surface-icon-gray-muted)',
        'surface-icon-gray-disabled': 'var(--surface-icon-gray-disabled)',
        'surface-icon-primary-normal': 'var(--surface-icon-primary-normal)',
        'surface-icon-on-sea-subtle': 'var(--surface-icon-on-sea-subtle)',
        'surface-icon-on-sea-intense': 'var(--surface-icon-on-sea-intense)',
        'surface-icon-on-cloud-subtle': 'var(--surface-icon-on-cloud-subtle)',
        'surface-icon-on-cloud-intense': 'var(--surface-icon-on-cloud-intense)',
        'surface-icon-static-white-normal': 'var(--surface-icon-static-white-normal)',
        'surface-icon-static-white-subtle': 'var(--surface-icon-static-white-subtle)',
        'surface-icon-static-white-muted': 'var(--surface-icon-static-white-muted)',
        'surface-icon-static-white-disabled': 'var(--surface-icon-static-white-disabled)',
        'surface-icon-static-black-normal': 'var(--surface-icon-static-black-normal)',
        'surface-icon-static-black-subtle': 'var(--surface-icon-static-black-subtle)',
        'surface-icon-static-black-muted': 'var(--surface-icon-static-black-muted)',
        'surface-icon-static-black-disabled': 'var(--surface-icon-static-black-disabled)',
        'feedback-background-positive-subtle': 'var(--feedback-background-positive-subtle)',
        'feedback-background-positive-intense': 'var(--feedback-background-positive-intense)',
        'feedback-background-negative-subtle': 'var(--feedback-background-negative-subtle)',
        'feedback-background-negative-intense': 'var(--feedback-background-negative-intense)',
        'feedback-background-notice-subtle': 'var(--feedback-background-notice-subtle)',
        'feedback-background-notice-intense': 'var(--feedback-background-notice-intense)',
        'feedback-background-information-subtle': 'var(--feedback-background-information-subtle)',
        'feedback-background-information-intense': 'var(--feedback-background-information-intense)',
        'feedback-background-neutral-subtle': 'var(--feedback-background-neutral-subtle)',
        'feedback-background-neutral-intense': 'var(--feedback-background-neutral-intense)',
        'feedback-border-positive-subtle': 'var(--feedback-border-positive-subtle)',
        'feedback-border-positive-intense': 'var(--feedback-border-positive-intense)',
        'feedback-border-negative-subtle': 'var(--feedback-border-negative-subtle)',
        'feedback-border-negative-intense': 'var(--feedback-border-negative-intense)',
        'feedback-border-notice-subtle': 'var(--feedback-border-notice-subtle)',
        'feedback-border-notice-intense': 'var(--feedback-border-notice-intense)',
        'feedback-border-information-subtle': 'var(--feedback-border-information-subtle)',
        'feedback-border-information-intense': 'var(--feedback-border-information-intense)',
        'feedback-border-neutral-subtle': 'var(--feedback-border-neutral-subtle)',
        'feedback-border-neutral-intense': 'var(--feedback-border-neutral-intense)',
        'feedback-text-positive-subtle': 'var(--feedback-text-positive-subtle)',
        'feedback-text-positive-intense': 'var(--feedback-text-positive-intense)',
        'feedback-text-negative-subtle': 'var(--feedback-text-negative-subtle)',
        'feedback-text-negative-intense': 'var(--feedback-text-negative-intense)',
        'feedback-text-notice-subtle': 'var(--feedback-text-notice-subtle)',
        'feedback-text-notice-intense': 'var(--feedback-text-notice-intense)',
        'feedback-text-information-subtle': 'var(--feedback-text-information-subtle)',
        'feedback-text-information-intense': 'var(--feedback-text-information-intense)',
        'feedback-text-neutral-subtle': 'var(--feedback-text-neutral-subtle)',
        'feedback-text-neutral-intense': 'var(--feedback-text-neutral-intense)',
        'feedback-icon-positive-subtle': 'var(--feedback-icon-positive-subtle)',
        'feedback-icon-positive-intense': 'var(--feedback-icon-positive-intense)',
        'feedback-icon-negative-subtle': 'var(--feedback-icon-negative-subtle)',
        'feedback-icon-negative-intense': 'var(--feedback-icon-negative-intense)',
        'feedback-icon-notice-subtle': 'var(--feedback-icon-notice-subtle)',
        'feedback-icon-notice-intense': 'var(--feedback-icon-notice-intense)',
        'feedback-icon-information-subtle': 'var(--feedback-icon-information-subtle)',
        'feedback-icon-information-intense': 'var(--feedback-icon-information-intense)',
        'feedback-icon-neutral-subtle': 'var(--feedback-icon-neutral-subtle)',
        'feedback-icon-neutral-intense': 'var(--feedback-icon-neutral-intense)',
        'interactive-background-positive-default': 'var(--interactive-background-positive-default)',
        'interactive-background-positive-highlighted':
          'var(--interactive-background-positive-highlighted)',
        'interactive-background-positive-disabled':
          'var(--interactive-background-positive-disabled)',
        'interactive-background-positive-faded': 'var(--interactive-background-positive-faded)',
        'interactive-background-positive-faded-highlighted':
          'var(--interactive-background-positive-faded-highlighted)',
        'interactive-background-negative-default': 'var(--interactive-background-negative-default)',
        'interactive-background-negative-highlighted':
          'var(--interactive-background-negative-highlighted)',
        'interactive-background-negative-disabled':
          'var(--interactive-background-negative-disabled)',
        'interactive-background-negative-faded': 'var(--interactive-background-negative-faded)',
        'interactive-background-negative-faded-highlighted':
          'var(--interactive-background-negative-faded-highlighted)',
        'interactive-background-notice-default': 'var(--interactive-background-notice-default)',
        'interactive-background-notice-highlighted':
          'var(--interactive-background-notice-highlighted)',
        'interactive-background-notice-disabled': 'var(--interactive-background-notice-disabled)',
        'interactive-background-notice-faded': 'var(--interactive-background-notice-faded)',
        'interactive-background-notice-faded-highlighted':
          'var(--interactive-background-notice-faded-highlighted)',
        'interactive-background-information-default':
          'var(--interactive-background-information-default)',
        'interactive-background-information-highlighted':
          'var(--interactive-background-information-highlighted)',
        'interactive-background-information-disabled':
          'var(--interactive-background-information-disabled)',
        'interactive-background-information-faded':
          'var(--interactive-background-information-faded)',
        'interactive-background-information-faded-highlighted':
          'var(--interactive-background-information-faded-highlighted)',
        'interactive-background-neutral-default': 'var(--interactive-background-neutral-default)',
        'interactive-background-neutral-highlighted':
          'var(--interactive-background-neutral-highlighted)',
        'interactive-background-neutral-disabled-solid':
          'var(--interactive-background-neutral-disabled-solid)',
        'interactive-background-neutral-disabled': 'var(--interactive-background-neutral-disabled)',
        'interactive-background-neutral-faded': 'var(--interactive-background-neutral-faded)',
        'interactive-background-neutral-faded-highlighted':
          'var(--interactive-background-neutral-faded-highlighted)',
        'interactive-background-gray-default': 'var(--interactive-background-gray-default)',
        'interactive-background-gray-highlighted': 'var(--interactive-background-gray-highlighted)',
        'interactive-background-gray-disabled': 'var(--interactive-background-gray-disabled)',
        'interactive-background-gray-faded': 'var(--interactive-background-gray-faded)',
        'interactive-background-gray-faded-highlighted':
          'var(--interactive-background-gray-faded-highlighted)',
        'interactive-background-gray-ghost': 'var(--interactive-background-gray-ghost)',
        'interactive-background-primary-default': 'var(--interactive-background-primary-default)',
        'interactive-background-primary-highlighted':
          'var(--interactive-background-primary-highlighted)',
        'interactive-background-primary-disabled': 'var(--interactive-background-primary-disabled)',
        'interactive-background-primary-faded': 'var(--interactive-background-primary-faded)',
        'interactive-background-primary-faded-highlighted':
          'var(--interactive-background-primary-faded-highlighted)',
        'interactive-background-static-black-default':
          'var(--interactive-background-static-black-default)',
        'interactive-background-static-black-highlighted':
          'var(--interactive-background-static-black-highlighted)',
        'interactive-background-static-black-disabled':
          'var(--interactive-background-static-black-disabled)',
        'interactive-background-static-black-faded':
          'var(--interactive-background-static-black-faded)',
        'interactive-background-static-black-faded-highlighted':
          'var(--interactive-background-static-black-faded-highlighted)',
        'interactive-background-static-black-ghost':
          'var(--interactive-background-static-black-ghost)',
        'interactive-background-static-white-default':
          'var(--interactive-background-static-white-default)',
        'interactive-background-static-white-highlighted':
          'var(--interactive-background-static-white-highlighted)',
        'interactive-background-static-white-disabled':
          'var(--interactive-background-static-white-disabled)',
        'interactive-background-static-white-faded':
          'var(--interactive-background-static-white-faded)',
        'interactive-background-static-white-faded-highlighted':
          'var(--interactive-background-static-white-faded-highlighted)',
        'interactive-background-static-white-ghost':
          'var(--interactive-background-static-white-ghost)',
        'interactive-border-positive-default': 'var(--interactive-border-positive-default)',
        'interactive-border-positive-highlighted': 'var(--interactive-border-positive-highlighted)',
        'interactive-border-positive-disabled': 'var(--interactive-border-positive-disabled)',
        'interactive-border-positive-faded': 'var(--interactive-border-positive-faded)',
        'interactive-border-negative-default': 'var(--interactive-border-negative-default)',
        'interactive-border-negative-highlighted': 'var(--interactive-border-negative-highlighted)',
        'interactive-border-negative-disabled': 'var(--interactive-border-negative-disabled)',
        'interactive-border-negative-faded': 'var(--interactive-border-negative-faded)',
        'interactive-border-notice-default': 'var(--interactive-border-notice-default)',
        'interactive-border-notice-highlighted': 'var(--interactive-border-notice-highlighted)',
        'interactive-border-notice-disabled': 'var(--interactive-border-notice-disabled)',
        'interactive-border-notice-faded': 'var(--interactive-border-notice-faded)',
        'interactive-border-information-default': 'var(--interactive-border-information-default)',
        'interactive-border-information-highlighted':
          'var(--interactive-border-information-highlighted)',
        'interactive-border-information-disabled': 'var(--interactive-border-information-disabled)',
        'interactive-border-information-faded': 'var(--interactive-border-information-faded)',
        'interactive-border-neutral-default': 'var(--interactive-border-neutral-default)',
        'interactive-border-neutral-highlighted': 'var(--interactive-border-neutral-highlighted)',
        'interactive-border-neutral-disabled': 'var(--interactive-border-neutral-disabled)',
        'interactive-border-neutral-faded': 'var(--interactive-border-neutral-faded)',
        'interactive-border-gray-default': 'var(--interactive-border-gray-default)',
        'interactive-border-gray-highlighted': 'var(--interactive-border-gray-highlighted)',
        'interactive-border-gray-disabled': 'var(--interactive-border-gray-disabled)',
        'interactive-border-gray-faded': 'var(--interactive-border-gray-faded)',
        'interactive-border-primary-default': 'var(--interactive-border-primary-default)',
        'interactive-border-primary-highlighted': 'var(--interactive-border-primary-highlighted)',
        'interactive-border-primary-disabled': 'var(--interactive-border-primary-disabled)',
        'interactive-border-primary-faded': 'var(--interactive-border-primary-faded)',
        'interactive-border-static-white-default': 'var(--interactive-border-static-white-default)',
        'interactive-border-static-white-highlighted':
          'var(--interactive-border-static-white-highlighted)',
        'interactive-border-static-white-disabled':
          'var(--interactive-border-static-white-disabled)',
        'interactive-border-static-white-faded': 'var(--interactive-border-static-white-faded)',
        'interactive-border-static-white-faded-highlighted':
          'var(--interactive-border-static-white-faded-highlighted)',
        'interactive-border-static-black-default': 'var(--interactive-border-static-black-default)',
        'interactive-border-static-black-highlighted':
          'var(--interactive-border-static-black-highlighted)',
        'interactive-border-static-black-disabled':
          'var(--interactive-border-static-black-disabled)',
        'interactive-border-static-black-faded': 'var(--interactive-border-static-black-faded)',
        'interactive-border-static-black-faded-highlighted':
          'var(--interactive-border-static-black-faded-highlighted)',
        'interactive-text-positive-normal': 'var(--interactive-text-positive-normal)',
        'interactive-text-positive-subtle': 'var(--interactive-text-positive-subtle)',
        'interactive-text-positive-muted': 'var(--interactive-text-positive-muted)',
        'interactive-text-positive-disabled': 'var(--interactive-text-positive-disabled)',
        'interactive-text-negative-normal': 'var(--interactive-text-negative-normal)',
        'interactive-text-negative-subtle': 'var(--interactive-text-negative-subtle)',
        'interactive-text-negative-muted': 'var(--interactive-text-negative-muted)',
        'interactive-text-negative-disabled': 'var(--interactive-text-negative-disabled)',
        'interactive-text-notice-normal': 'var(--interactive-text-notice-normal)',
        'interactive-text-notice-subtle': 'var(--interactive-text-notice-subtle)',
        'interactive-text-notice-muted': 'var(--interactive-text-notice-muted)',
        'interactive-text-notice-disabled': 'var(--interactive-text-notice-disabled)',
        'interactive-text-information-normal': 'var(--interactive-text-information-normal)',
        'interactive-text-information-subtle': 'var(--interactive-text-information-subtle)',
        'interactive-text-information-muted': 'var(--interactive-text-information-muted)',
        'interactive-text-information-disabled': 'var(--interactive-text-information-disabled)',
        'interactive-text-neutral-normal': 'var(--interactive-text-neutral-normal)',
        'interactive-text-neutral-subtle': 'var(--interactive-text-neutral-subtle)',
        'interactive-text-neutral-muted': 'var(--interactive-text-neutral-muted)',
        'interactive-text-neutral-disabled': 'var(--interactive-text-neutral-disabled)',
        'interactive-text-gray-normal': 'var(--interactive-text-gray-normal)',
        'interactive-text-gray-subtle': 'var(--interactive-text-gray-subtle)',
        'interactive-text-gray-muted': 'var(--interactive-text-gray-muted)',
        'interactive-text-gray-disabled': 'var(--interactive-text-gray-disabled)',
        'interactive-text-primary-normal': 'var(--interactive-text-primary-normal)',
        'interactive-text-primary-subtle': 'var(--interactive-text-primary-subtle)',
        'interactive-text-primary-muted': 'var(--interactive-text-primary-muted)',
        'interactive-text-primary-disabled': 'var(--interactive-text-primary-disabled)',
        'interactive-text-on-primary-normal': 'var(--interactive-text-on-primary-normal)',
        'interactive-text-on-primary-subtle': 'var(--interactive-text-on-primary-subtle)',
        'interactive-text-on-primary-muted': 'var(--interactive-text-on-primary-muted)',
        'interactive-text-on-primary-disabled': 'var(--interactive-text-on-primary-disabled)',
        'interactive-text-on-neutral-normal': 'var(--interactive-text-on-neutral-normal)',
        'interactive-text-on-neutral-subtle': 'var(--interactive-text-on-neutral-subtle)',
        'interactive-text-on-neutral-muted': 'var(--interactive-text-on-neutral-muted)',
        'interactive-text-on-neutral-disabled': 'var(--interactive-text-on-neutral-disabled)',
        'interactive-text-static-white-normal': 'var(--interactive-text-static-white-normal)',
        'interactive-text-static-white-subtle': 'var(--interactive-text-static-white-subtle)',
        'interactive-text-static-white-muted': 'var(--interactive-text-static-white-muted)',
        'interactive-text-static-white-disabled': 'var(--interactive-text-static-white-disabled)',
        'interactive-text-static-black-normal': 'var(--interactive-text-static-black-normal)',
        'interactive-text-static-black-subtle': 'var(--interactive-text-static-black-subtle)',
        'interactive-text-static-black-muted': 'var(--interactive-text-static-black-muted)',
        'interactive-text-static-black-disabled': 'var(--interactive-text-static-black-disabled)',
        'interactive-icon-positive-normal': 'var(--interactive-icon-positive-normal)',
        'interactive-icon-positive-subtle': 'var(--interactive-icon-positive-subtle)',
        'interactive-icon-positive-muted': 'var(--interactive-icon-positive-muted)',
        'interactive-icon-positive-disabled': 'var(--interactive-icon-positive-disabled)',
        'interactive-icon-negative-normal': 'var(--interactive-icon-negative-normal)',
        'interactive-icon-negative-subtle': 'var(--interactive-icon-negative-subtle)',
        'interactive-icon-negative-muted': 'var(--interactive-icon-negative-muted)',
        'interactive-icon-negative-disabled': 'var(--interactive-icon-negative-disabled)',
        'interactive-icon-notice-normal': 'var(--interactive-icon-notice-normal)',
        'interactive-icon-notice-subtle': 'var(--interactive-icon-notice-subtle)',
        'interactive-icon-notice-muted': 'var(--interactive-icon-notice-muted)',
        'interactive-icon-notice-disabled': 'var(--interactive-icon-notice-disabled)',
        'interactive-icon-information-normal': 'var(--interactive-icon-information-normal)',
        'interactive-icon-information-subtle': 'var(--interactive-icon-information-subtle)',
        'interactive-icon-information-muted': 'var(--interactive-icon-information-muted)',
        'interactive-icon-information-disabled': 'var(--interactive-icon-information-disabled)',
        'interactive-icon-neutral-normal': 'var(--interactive-icon-neutral-normal)',
        'interactive-icon-neutral-subtle': 'var(--interactive-icon-neutral-subtle)',
        'interactive-icon-neutral-muted': 'var(--interactive-icon-neutral-muted)',
        'interactive-icon-neutral-disabled': 'var(--interactive-icon-neutral-disabled)',
        'interactive-icon-gray-normal': 'var(--interactive-icon-gray-normal)',
        'interactive-icon-gray-subtle': 'var(--interactive-icon-gray-subtle)',
        'interactive-icon-gray-muted': 'var(--interactive-icon-gray-muted)',
        'interactive-icon-gray-disabled': 'var(--interactive-icon-gray-disabled)',
        'interactive-icon-primary-normal': 'var(--interactive-icon-primary-normal)',
        'interactive-icon-primary-subtle': 'var(--interactive-icon-primary-subtle)',
        'interactive-icon-primary-muted': 'var(--interactive-icon-primary-muted)',
        'interactive-icon-primary-disabled': 'var(--interactive-icon-primary-disabled)',
        'interactive-icon-on-primary-normal': 'var(--interactive-icon-on-primary-normal)',
        'interactive-icon-on-primary-subtle': 'var(--interactive-icon-on-primary-subtle)',
        'interactive-icon-on-primary-muted': 'var(--interactive-icon-on-primary-muted)',
        'interactive-icon-on-primary-disabled': 'var(--interactive-icon-on-primary-disabled)',
        'interactive-icon-on-neutral-normal': 'var(--interactive-icon-on-neutral-normal)',
        'interactive-icon-on-neutral-subtle': 'var(--interactive-icon-on-neutral-subtle)',
        'interactive-icon-on-neutral-muted': 'var(--interactive-icon-on-neutral-muted)',
        'interactive-icon-on-neutral-disabled': 'var(--interactive-icon-on-neutral-disabled)',
        'interactive-icon-static-white-normal': 'var(--interactive-icon-static-white-normal)',
        'interactive-icon-static-white-subtle': 'var(--interactive-icon-static-white-subtle)',
        'interactive-icon-static-white-muted': 'var(--interactive-icon-static-white-muted)',
        'interactive-icon-static-white-disabled': 'var(--interactive-icon-static-white-disabled)',
        'interactive-icon-static-black-normal': 'var(--interactive-icon-static-black-normal)',
        'interactive-icon-static-black-subtle': 'var(--interactive-icon-static-black-subtle)',
        'interactive-icon-static-black-muted': 'var(--interactive-icon-static-black-muted)',
        'interactive-icon-static-black-disabled': 'var(--interactive-icon-static-black-disabled)',
        'overlay-background-moderate': 'var(--overlay-background-moderate)',
        'overlay-background-subtle': 'var(--overlay-background-subtle)',
        'popup-background-subtle': 'var(--popup-background-subtle)',
        'popup-background-intense': 'var(--popup-background-intense)',
        'popup-background-gray-subtle': 'var(--popup-background-gray-subtle)',
        'popup-background-gray-moderate': 'var(--popup-background-gray-moderate)',
        'popup-background-gray-intense': 'var(--popup-background-gray-intense)',
        'popup-background-positive-moderate': 'var(--popup-background-positive-moderate)',
        'popup-background-negative-moderate': 'var(--popup-background-negative-moderate)',
        'popup-background-notice-moderate': 'var(--popup-background-notice-moderate)',
        'popup-background-information-moderate': 'var(--popup-background-information-moderate)',
        'popup-background-neutral-moderate': 'var(--popup-background-neutral-moderate)',
        'popup-border-subtle': 'var(--popup-border-subtle)',
        'popup-border-intense': 'var(--popup-border-intense)',
        'popup-border-gray-subtle': 'var(--popup-border-gray-subtle)',
        'popup-border-gray-moderate': 'var(--popup-border-gray-moderate)',
        'popup-border-gray-intense': 'var(--popup-border-gray-intense)',
        'popup-border-positive-moderate': 'var(--popup-border-positive-moderate)',
        'popup-border-negative-moderate': 'var(--popup-border-negative-moderate)',
        'popup-border-notice-moderate': 'var(--popup-border-notice-moderate)',
        'popup-border-information-moderate': 'var(--popup-border-information-moderate)',
        'popup-border-neutral-moderate': 'var(--popup-border-neutral-moderate)',
        'data-background-categorical-blue-faint': 'var(--data-background-categorical-blue-faint)',
        'data-background-categorical-blue-subtle': 'var(--data-background-categorical-blue-subtle)',
        'data-background-categorical-blue-moderate':
          'var(--data-background-categorical-blue-moderate)',
        'data-background-categorical-blue-intense':
          'var(--data-background-categorical-blue-intense)',
        'data-background-categorical-blue-strong': 'var(--data-background-categorical-blue-strong)',
        'data-background-categorical-green-faint': 'var(--data-background-categorical-green-faint)',
        'data-background-categorical-green-subtle':
          'var(--data-background-categorical-green-subtle)',
        'data-background-categorical-green-moderate':
          'var(--data-background-categorical-green-moderate)',
        'data-background-categorical-green-intense':
          'var(--data-background-categorical-green-intense)',
        'data-background-categorical-green-strong':
          'var(--data-background-categorical-green-strong)',
        'data-background-categorical-red-faint': 'var(--data-background-categorical-red-faint)',
        'data-background-categorical-red-subtle': 'var(--data-background-categorical-red-subtle)',
        'data-background-categorical-red-moderate':
          'var(--data-background-categorical-red-moderate)',
        'data-background-categorical-red-intense': 'var(--data-background-categorical-red-intense)',
        'data-background-categorical-red-strong': 'var(--data-background-categorical-red-strong)',
        'data-background-categorical-orange-faint':
          'var(--data-background-categorical-orange-faint)',
        'data-background-categorical-orange-subtle':
          'var(--data-background-categorical-orange-subtle)',
        'data-background-categorical-orange-moderate':
          'var(--data-background-categorical-orange-moderate)',
        'data-background-categorical-orange-intense':
          'var(--data-background-categorical-orange-intense)',
        'data-background-categorical-orange-strong':
          'var(--data-background-categorical-orange-strong)',
        'data-background-categorical-sky-blue-faint':
          'var(--data-background-categorical-sky-blue-faint)',
        'data-background-categorical-sky-blue-subtle':
          'var(--data-background-categorical-sky-blue-subtle)',
        'data-background-categorical-sky-blue-moderate':
          'var(--data-background-categorical-sky-blue-moderate)',
        'data-background-categorical-sky-blue-intense':
          'var(--data-background-categorical-sky-blue-intense)',
        'data-background-categorical-sky-blue-strong':
          'var(--data-background-categorical-sky-blue-strong)',
        'data-background-categorical-purple-faint':
          'var(--data-background-categorical-purple-faint)',
        'data-background-categorical-purple-subtle':
          'var(--data-background-categorical-purple-subtle)',
        'data-background-categorical-purple-moderate':
          'var(--data-background-categorical-purple-moderate)',
        'data-background-categorical-purple-intense':
          'var(--data-background-categorical-purple-intense)',
        'data-background-categorical-purple-strong':
          'var(--data-background-categorical-purple-strong)',
        'data-background-categorical-pink-faint': 'var(--data-background-categorical-pink-faint)',
        'data-background-categorical-pink-subtle': 'var(--data-background-categorical-pink-subtle)',
        'data-background-categorical-pink-moderate':
          'var(--data-background-categorical-pink-moderate)',
        'data-background-categorical-pink-intense':
          'var(--data-background-categorical-pink-intense)',
        'data-background-categorical-pink-strong': 'var(--data-background-categorical-pink-strong)',
        'data-background-categorical-gold-faint': 'var(--data-background-categorical-gold-faint)',
        'data-background-categorical-gold-subtle': 'var(--data-background-categorical-gold-subtle)',
        'data-background-categorical-gold-moderate':
          'var(--data-background-categorical-gold-moderate)',
        'data-background-categorical-gold-intense':
          'var(--data-background-categorical-gold-intense)',
        'data-background-categorical-gold-strong': 'var(--data-background-categorical-gold-strong)',
        'data-background-categorical-gray-faint': 'var(--data-background-categorical-gray-faint)',
        'data-background-categorical-gray-subtle': 'var(--data-background-categorical-gray-subtle)',
        'data-background-categorical-gray-moderate':
          'var(--data-background-categorical-gray-moderate)',
        'data-background-categorical-gray-intense':
          'var(--data-background-categorical-gray-intense)',
        'data-background-categorical-gray-strong': 'var(--data-background-categorical-gray-strong)',
        'data-background-sequential-blue-50': 'var(--data-background-sequential-blue-50)',
        'data-background-sequential-blue-100': 'var(--data-background-sequential-blue-100)',
        'data-background-sequential-blue-200': 'var(--data-background-sequential-blue-200)',
        'data-background-sequential-blue-300': 'var(--data-background-sequential-blue-300)',
        'data-background-sequential-blue-400': 'var(--data-background-sequential-blue-400)',
        'data-background-sequential-blue-500': 'var(--data-background-sequential-blue-500)',
        'data-background-sequential-blue-600': 'var(--data-background-sequential-blue-600)',
        'data-background-sequential-blue-700': 'var(--data-background-sequential-blue-700)',
        'data-background-sequential-blue-800': 'var(--data-background-sequential-blue-800)',
        'data-background-sequential-blue-900': 'var(--data-background-sequential-blue-900)',
        'data-background-sequential-blue-1000': 'var(--data-background-sequential-blue-1000)',
        'data-background-sequential-green-50': 'var(--data-background-sequential-green-50)',
        'data-background-sequential-green-100': 'var(--data-background-sequential-green-100)',
        'data-background-sequential-green-200': 'var(--data-background-sequential-green-200)',
        'data-background-sequential-green-300': 'var(--data-background-sequential-green-300)',
        'data-background-sequential-green-400': 'var(--data-background-sequential-green-400)',
        'data-background-sequential-green-500': 'var(--data-background-sequential-green-500)',
        'data-background-sequential-green-600': 'var(--data-background-sequential-green-600)',
        'data-background-sequential-green-700': 'var(--data-background-sequential-green-700)',
        'data-background-sequential-green-800': 'var(--data-background-sequential-green-800)',
        'data-background-sequential-green-900': 'var(--data-background-sequential-green-900)',
        'data-background-sequential-green-1000': 'var(--data-background-sequential-green-1000)',
        'data-background-sequential-red-50': 'var(--data-background-sequential-red-50)',
        'data-background-sequential-red-100': 'var(--data-background-sequential-red-100)',
        'data-background-sequential-red-200': 'var(--data-background-sequential-red-200)',
        'data-background-sequential-red-300': 'var(--data-background-sequential-red-300)',
        'data-background-sequential-red-400': 'var(--data-background-sequential-red-400)',
        'data-background-sequential-red-500': 'var(--data-background-sequential-red-500)',
        'data-background-sequential-red-600': 'var(--data-background-sequential-red-600)',
        'data-background-sequential-red-700': 'var(--data-background-sequential-red-700)',
        'data-background-sequential-red-800': 'var(--data-background-sequential-red-800)',
        'data-background-sequential-red-900': 'var(--data-background-sequential-red-900)',
        'data-background-sequential-red-1000': 'var(--data-background-sequential-red-1000)',
        'data-background-sequential-orange-50': 'var(--data-background-sequential-orange-50)',
        'data-background-sequential-orange-100': 'var(--data-background-sequential-orange-100)',
        'data-background-sequential-orange-200': 'var(--data-background-sequential-orange-200)',
        'data-background-sequential-orange-300': 'var(--data-background-sequential-orange-300)',
        'data-background-sequential-orange-400': 'var(--data-background-sequential-orange-400)',
        'data-background-sequential-orange-500': 'var(--data-background-sequential-orange-500)',
        'data-background-sequential-orange-600': 'var(--data-background-sequential-orange-600)',
        'data-background-sequential-orange-700': 'var(--data-background-sequential-orange-700)',
        'data-background-sequential-orange-800': 'var(--data-background-sequential-orange-800)',
        'data-background-sequential-orange-900': 'var(--data-background-sequential-orange-900)',
        'data-background-sequential-orange-1000': 'var(--data-background-sequential-orange-1000)',
        'data-background-sequential-sky-blue-50': 'var(--data-background-sequential-sky-blue-50)',
        'data-background-sequential-sky-blue-100': 'var(--data-background-sequential-sky-blue-100)',
        'data-background-sequential-sky-blue-200': 'var(--data-background-sequential-sky-blue-200)',
        'data-background-sequential-sky-blue-300': 'var(--data-background-sequential-sky-blue-300)',
        'data-background-sequential-sky-blue-400': 'var(--data-background-sequential-sky-blue-400)',
        'data-background-sequential-sky-blue-500': 'var(--data-background-sequential-sky-blue-500)',
        'data-background-sequential-sky-blue-600': 'var(--data-background-sequential-sky-blue-600)',
        'data-background-sequential-sky-blue-700': 'var(--data-background-sequential-sky-blue-700)',
        'data-background-sequential-sky-blue-800': 'var(--data-background-sequential-sky-blue-800)',
        'data-background-sequential-sky-blue-900': 'var(--data-background-sequential-sky-blue-900)',
        'data-background-sequential-sky-blue-1000':
          'var(--data-background-sequential-sky-blue-1000)',
        'data-background-sequential-purple-50': 'var(--data-background-sequential-purple-50)',
        'data-background-sequential-purple-100': 'var(--data-background-sequential-purple-100)',
        'data-background-sequential-purple-200': 'var(--data-background-sequential-purple-200)',
        'data-background-sequential-purple-300': 'var(--data-background-sequential-purple-300)',
        'data-background-sequential-purple-400': 'var(--data-background-sequential-purple-400)',
        'data-background-sequential-purple-500': 'var(--data-background-sequential-purple-500)',
        'data-background-sequential-purple-600': 'var(--data-background-sequential-purple-600)',
        'data-background-sequential-purple-700': 'var(--data-background-sequential-purple-700)',
        'data-background-sequential-purple-800': 'var(--data-background-sequential-purple-800)',
        'data-background-sequential-purple-900': 'var(--data-background-sequential-purple-900)',
        'data-background-sequential-purple-1000': 'var(--data-background-sequential-purple-1000)',
        'data-background-sequential-pink-50': 'var(--data-background-sequential-pink-50)',
        'data-background-sequential-pink-100': 'var(--data-background-sequential-pink-100)',
        'data-background-sequential-pink-200': 'var(--data-background-sequential-pink-200)',
        'data-background-sequential-pink-300': 'var(--data-background-sequential-pink-300)',
        'data-background-sequential-pink-400': 'var(--data-background-sequential-pink-400)',
        'data-background-sequential-pink-500': 'var(--data-background-sequential-pink-500)',
        'data-background-sequential-pink-600': 'var(--data-background-sequential-pink-600)',
        'data-background-sequential-pink-700': 'var(--data-background-sequential-pink-700)',
        'data-background-sequential-pink-800': 'var(--data-background-sequential-pink-800)',
        'data-background-sequential-pink-900': 'var(--data-background-sequential-pink-900)',
        'data-background-sequential-pink-1000': 'var(--data-background-sequential-pink-1000)',
        'data-background-sequential-gold-50': 'var(--data-background-sequential-gold-50)',
        'data-background-sequential-gold-100': 'var(--data-background-sequential-gold-100)',
        'data-background-sequential-gold-200': 'var(--data-background-sequential-gold-200)',
        'data-background-sequential-gold-300': 'var(--data-background-sequential-gold-300)',
        'data-background-sequential-gold-400': 'var(--data-background-sequential-gold-400)',
        'data-background-sequential-gold-500': 'var(--data-background-sequential-gold-500)',
        'data-background-sequential-gold-600': 'var(--data-background-sequential-gold-600)',
        'data-background-sequential-gold-700': 'var(--data-background-sequential-gold-700)',
        'data-background-sequential-gold-800': 'var(--data-background-sequential-gold-800)',
        'data-background-sequential-gold-900': 'var(--data-background-sequential-gold-900)',
        'data-background-sequential-gold-1000': 'var(--data-background-sequential-gold-1000)',
        'data-background-sequential-gray-0': 'var(--data-background-sequential-gray-0)',
        'data-background-sequential-gray-50': 'var(--data-background-sequential-gray-50)',
        'data-background-sequential-gray-100': 'var(--data-background-sequential-gray-100)',
        'data-background-sequential-gray-200': 'var(--data-background-sequential-gray-200)',
        'data-background-sequential-gray-300': 'var(--data-background-sequential-gray-300)',
        'data-background-sequential-gray-400': 'var(--data-background-sequential-gray-400)',
        'data-background-sequential-gray-500': 'var(--data-background-sequential-gray-500)',
        'data-background-sequential-gray-600': 'var(--data-background-sequential-gray-600)',
        'data-background-sequential-gray-700': 'var(--data-background-sequential-gray-700)',
        'data-background-sequential-gray-800': 'var(--data-background-sequential-gray-800)',
        'data-background-sequential-gray-900': 'var(--data-background-sequential-gray-900)',
        'data-background-sequential-gray-1000': 'var(--data-background-sequential-gray-1000)',
        transparent: 'var(--transparent)',
      },
      spacing: {
        'spacing-0': 'var(--spacing-0)',
        'spacing-1': 'var(--spacing-1)',
        'spacing-2': 'var(--spacing-2)',
        'spacing-3': 'var(--spacing-3)',
        'spacing-4': 'var(--spacing-4)',
        'spacing-5': 'var(--spacing-5)',
        'spacing-6': 'var(--spacing-6)',
        'spacing-7': 'var(--spacing-7)',
        'spacing-8': 'var(--spacing-8)',
        'spacing-9': 'var(--spacing-9)',
        'spacing-10': 'var(--spacing-10)',
        'spacing-11': 'var(--spacing-11)',
      },
      borderRadius: {
        none: 'var(--border-radius-none)',
        '2xsmall': 'var(--border-radius-2xsmall)',
        xsmall: 'var(--border-radius-xsmall)',
        small: 'var(--border-radius-small)',
        medium: 'var(--border-radius-medium)',
        large: 'var(--border-radius-large)',
        xlarge: 'var(--border-radius-xlarge)',
        '2xlarge': 'var(--border-radius-2xlarge)',
        max: 'var(--border-radius-max)',
        round: 'var(--border-radius-round)',
      },
      borderWidth: {
        none: 'var(--border-width-none)',
        thinner: 'var(--border-width-thinner)',
        thin: 'var(--border-width-thin)',
        thick: 'var(--border-width-thick)',
        thicker: 'var(--border-width-thicker)',
      },
      opacity: {
        56: '0.56',
        64: '0.64',
      },
      screens: {
        base: '0px',
        xs: '320px',
        s: '480px',
        m: '768px',
        l: '1024px',
        xl: '1200px',
      },
      fontFamily: {
        text: ['var(--font-family-text)'],
        heading: ['var(--font-family-heading)'],
        code: ['var(--font-family-code)'],
      },
      fontSize: {
        25: 'var(--font-size-25)',
        50: 'var(--font-size-50)',
        75: 'var(--font-size-75)',
        100: 'var(--font-size-100)',
        200: 'var(--font-size-200)',
        300: 'var(--font-size-300)',
        400: 'var(--font-size-400)',
        500: 'var(--font-size-500)',
        600: 'var(--font-size-600)',
        700: 'var(--font-size-700)',
        800: 'var(--font-size-800)',
        900: 'var(--font-size-900)',
        1000: 'var(--font-size-1000)',
        1100: 'var(--font-size-1100)',
      },
      fontWeight: {
        regular: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      lineHeight: {
        0: 'var(--line-height-0)',
        25: 'var(--line-height-25)',
        50: 'var(--line-height-50)',
        75: 'var(--line-height-75)',
        100: 'var(--line-height-100)',
        200: 'var(--line-height-200)',
        300: 'var(--line-height-300)',
        400: 'var(--line-height-400)',
        500: 'var(--line-height-500)',
        600: 'var(--line-height-600)',
        700: 'var(--line-height-700)',
        800: 'var(--line-height-800)',
        900: 'var(--line-height-900)',
        1000: 'var(--line-height-1000)',
        1100: 'var(--line-height-1100)',
      },
      letterSpacing: {
        25: 'var(--letter-spacing-25)',
        50: 'var(--letter-spacing-50)',
        100: 'var(--letter-spacing-100)',
      },
      transitionDuration: {
        '2xquick': 'var(--duration-2xquick)',
        xquick: 'var(--duration-xquick)',
        quick: 'var(--duration-quick)',
        moderate: 'var(--duration-moderate)',
        xmoderate: 'var(--duration-xmoderate)',
        gentle: 'var(--duration-gentle)',
        xgentle: 'var(--duration-xgentle)',
        '2xgentle': 'var(--duration-2xgentle)',
      },
      transitionDelay: {
        '2xquick': 'var(--delay-2xquick)',
        xquick: 'var(--delay-xquick)',
        moderate: 'var(--delay-moderate)',
        gentle: 'var(--delay-gentle)',
        xgentle: 'var(--delay-xgentle)',
        long: 'var(--delay-long)',
        xlong: 'var(--delay-xlong)',
        '2xlong': 'var(--delay-2xlong)',
      },
      transitionTimingFunction: {
        linear: 'var(--easing-linear)',
        entrance: 'var(--easing-entrance)',
        exit: 'var(--easing-exit)',
        standard: 'var(--easing-standard)',
        emphasized: 'var(--easing-emphasized)',
        overshoot: 'var(--easing-overshoot)',
        shake: 'var(--easing-shake)',
      },
    },
  },
  plugins: [plugin],
};
