import React from 'react';
import {
  Card,
  CardBody,
  CardHeader,
  CardHeaderCounter,
  CardHeaderIcon,
  CardHeaderLeading,
  CardHeaderTrailing,
} from '../Card';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Card,
  'https://www.figma.com/design/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=72099-253612&m=dev',
  {
    props: {
      elevation: figma.enum('elevation', {
        None: undefined,
        highRaised: 'highRaised',
        lowRaised: 'lowRaised',
        midRaised: 'midRaised',
      }),
      cardHeader: figma.nestedProps('_Card/Header', {
        title: figma.textContent('title'),
        subtitle: figma.textContent('subtitle'),
      }),
      cardHeaderLeading: figma.nestedProps('_Card/ Leading Item', {
        leadingIcon: figma.instance('leadingIcon'),
      }),
      cardHeaderTrailing: figma.nestedProps('_Card/Trailing Item', {
        trailing: figma.instance('trailing'),
      }),
      cardHeaderAvatar: figma.nestedProps('Avatar', {
        size: figma.enum('size', {
          Small: 'small',
          Medium: 'medium',
          Large: 'large',
        }),
      }),
      cardHeaderCounter: figma.nestedProps('Counter', {
        color: figma.enum('color', {
          Primary: 'primary',
          Neutral: 'neutral',
          Information: 'information',
          Notice: 'notice',
          Positive: 'positive',
          Negative: 'negative',
        }),
        count: figma.string('label'),
        emphasis: figma.enum('emphasis', {
          Subtle: 'subtle',
          Intense: 'intense',
        }),
        size: figma.enum('size', {
          Small: 'small',
          Medium: 'medium',
          Large: 'large',
        }),
      }),
    },
    example: ({
      elevation,
      cardHeader,
      cardHeaderLeading,
      cardHeaderCounter,
      cardHeaderTrailing,
    }) => (
      <Card elevation={elevation}>
        <CardHeader>
          <CardHeaderLeading
            title={cardHeader.title}
            subtitle={cardHeader.subtitle}
            prefix={<CardHeaderIcon icon={cardHeaderLeading.leadingIcon} />}
            suffix={
              <CardHeaderCounter
                color={cardHeaderCounter.color}
                count={cardHeaderCounter.count}
                emphasis={cardHeaderCounter.emphasis}
                size={cardHeaderCounter.size}
              />
            }
          />
          <CardHeaderTrailing visual={cardHeaderTrailing.trailing} />
        </CardHeader>
        <CardBody>{/* Add your content here */}</CardBody>
      </Card>
    ),
  },
);
