import React from 'react';
import figma from '@figma/code-connect';
import {
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  CardHeaderLeading,
  CardHeaderTrailing,
  CardHeaderIcon,
  CardHeaderCounter,
} from './';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Card,
  'https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade-DSL?type=design&node-id=72099-253612&mode=dev',
  {
    props: {
      showFooter: figma.boolean('showFooter'),
      showHeader: figma.boolean('showHeader'),
      children: figma.children(['_Card/Header', '_Card/Footer']),
      screenSize: figma.enum('screenSize', {
        Mobile: 'mobile',
        Desktop: 'desktop',
      }),
      state: figma.enum('state', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        'Hover-scaled': 'hover-scaled',
      }),
      elevation: figma.enum('elevation', {
        None: 'none',
        highRaised: 'highRaised',
        lowRaised: 'lowRaised',
        midRaised: 'midRaised',
      }),
    },
    example: ({ elevation, children }) => <Card elevation={elevation} children={children} />,
  },
);

figma.connect(
  CardHeader,
  'https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=72069-196853&mode=dev',
  {
    props: {
      showTrailingItem: figma.boolean('showTrailingItem'),
      showLeadingIcon: figma.boolean('showLeading_Icon'),
      showCounter: figma.boolean('showCounter'),
      leadingIcon: figma.instance('leadingIcon'),
      showDivider: figma.boolean('showDivider'),
      showSubtitle: figma.boolean('showSubtitle'),
      screenSize: figma.enum('screenSize', {
        Desktop: 'desktop',
        Mobile: 'mobile',
      }),
    },
    example: ({ showDivider, showLeadingIcon, showTrailingItem, showCounter, leadingIcon }) => {
      if (showLeadingIcon && leadingIcon && showCounter && showTrailingItem) {
        return (
          <CardHeader showDivider={showDivider}>
            <CardHeaderLeading title="Card Title" subtitle="Card Subtitle" />
            <CardHeaderTrailing />
          </CardHeader>
        );
      }

      if (showLeadingIcon && leadingIcon && showCounter) {
        return (
          <CardHeader showDivider={showDivider}>
            <CardHeaderLeading
              prefix={<CardHeaderIcon icon={leadingIcon} />}
              title="Card Title"
              subtitle="Card Subtitle"
              suffix={<CardHeaderCounter value={5} />}
            />
          </CardHeader>
        );
      }

      if (showLeadingIcon && leadingIcon) {
        return (
          <CardHeader showDivider={showDivider}>
            <CardHeaderLeading
              prefix={<CardHeaderIcon icon={leadingIcon} />}
              title="Card Title"
              subtitle="Card Subtitle"
            />
          </CardHeader>
        );
      }

      if (showTrailingItem) {
        return (
          <CardHeader showDivider={showDivider}>
            <CardHeaderTrailing />
          </CardHeader>
        );
      }
    },
  },
);
