import React from 'react';
import { Radio } from './Radio';
import figma from '@figma/code-connect';
import { RadioGroup } from './RadioGroup';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Radio,
  'https://www.figma.com/design/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=71905-62364&m=dev',
  {
    props: {
      children: figma.boolean('label'),
      helpText: figma.boolean('showHelpText'),
      size: figma.enum('size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large',
      }),
      validationState: figma.enum('validationState', {
        Error: 'error',
      }),
    },
    example: ({ children, ...props }) => (
      <Radio
        value="" // add radio value here
        {...props}
      >
        {children}
      </Radio>
    ),
  },
);

figma.connect(
  RadioGroup,
  'https://www.figma.com/design/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=71971-26042&m=dev',
  {
    props: {
      label: figma.boolean('showLabel'),
      isDisabled: figma.boolean('isDisabled'),
      helpText: figma.boolean('showHelpText'),
      size: figma.enum('size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large',
      }),
      validationState: figma.enum('validationState', {
        Error: 'error',
      }),
      labelPosition: figma.enum('labelPosition', {
        Top: 'top',
        Left: 'left',
      }),
    },

    example: ({ helpText, label, ...props }) => (
      <RadioGroup
        {...props}
        helpText={helpText} // Add help text here
        label={label} // Add label here
      >
        {/* Add Radio components here */}
      </RadioGroup>
    ),
  },
);
