/**
 * Tabs template classes (Tailwind).
 *
 * Pure layout/padding/radius/color are literal Tailwind utilities. The tab button's descendant
 * text/icon color rules (crossed with hover/disabled/selected/variant state), `!important`
 * border-color resets, the scrollbar-hiding pseudo-element, and `:focus-visible` box-shadow +
 * compound radius all live in the `.blade-tabs-*` plugin classes (see `tailwind/plugin.cjs`).
 * Marker classes (`blade-tabs-selected`, `blade-tabs-filled-unselected`, `blade-tabs-disabled-link`,
 * `blade-tabs-bg-transparent`) carry no declaration of their own beyond what's combined here —
 * they only need to match the plugin's compound selectors.
 */
export const getTabsTemplateClasses = (): Record<string, string> => ({
  tabsWrapper: 'flex',
  tabsHorizontal: 'flex-col',
  tabsVertical: 'flex-row',
  tabListOuter: 'shrink-0 overflow-hidden',
  tabListOuterHorizontal: 'block',
  tabListOuterVertical: 'flex',
  tabListScrollRow: 'flex flex-row',
  scrollableArea: 'blade-tabs-scrollable-area',
  tabListInner: 'flex w-full',
  tabListHorizontal: 'flex-row items-center',
  tabListVertical: 'flex-col items-start overflow-hidden',
  tabListFilled:
    'rounded-medium border-0 border-interactive-border-gray-default p-spacing-2 gap-spacing-1 bg-interactive-background-gray-faded',
  tabListFilledCompact: 'rounded-small p-spacing-1',
  tabListFilledVertical: 'gap-spacing-0',
  tabListBordered: 'p-spacing-0 gap-spacing-8',
  tabListBorderedVertical: 'gap-spacing-0',
  verticalTrack: 'blade-tabs-vertical-track',
  horizontalTrack: 'blade-tabs-horizontal-track',
  tabButton: 'blade-tabs-button',
  tabButtonHorizontal: 'justify-center',
  tabButtonVertical: '[justify-content:left]',
  tabButtonFullWidth: 'w-full',
  tabBorderedHorizSmall: 'pt-spacing-0 pb-spacing-3 pl-spacing-0 pr-spacing-0',
  tabBorderedHorizMedium: 'pt-spacing-2 pb-spacing-4 pl-spacing-0 pr-spacing-0',
  tabBorderedHorizLarge: 'pt-spacing-4 pb-spacing-4 pl-spacing-0 pr-spacing-0',
  tabBorderedVertSmall: 'pt-spacing-1 pb-spacing-1 pl-spacing-4 pr-spacing-4',
  tabBorderedVertMedium: 'pt-spacing-2 pb-spacing-2 pl-spacing-4 pr-spacing-4',
  tabBorderedVertLarge: 'pt-spacing-3 pb-spacing-3 pl-spacing-4 pr-spacing-4',
  tabFilledHorizSmall: 'pt-spacing-1 pb-spacing-1 pl-spacing-3 pr-spacing-3',
  tabFilledHorizMedium: 'pt-spacing-2 pb-spacing-2 pl-spacing-3 pr-spacing-3',
  tabFilledHorizLarge: 'pt-spacing-3 pb-spacing-3 pl-spacing-3 pr-spacing-3',
  tabFilledVertSmall: 'pt-spacing-3 pb-spacing-3 pl-spacing-4 pr-spacing-4',
  tabFilledVertMedium: 'pt-spacing-4 pb-spacing-4 pl-spacing-4 pr-spacing-4',
  tabFilledVertLarge: 'pt-spacing-4 pb-spacing-4 pl-spacing-4 pr-spacing-4',
  tabBorderedBorderBottom: 'blade-tabs-bordered-border-bottom',
  tabBorderedBorderLeft: 'blade-tabs-bordered-border-left',
  tabRadiusNone: 'rounded-none',
  tabRadiusSmall: 'rounded-small',
  tabRadiusMedium: 'rounded-medium',
  tabRadiusFilledHorizSmall: 'rounded-xsmall',
  tabBgTransparent: 'bg-transparent blade-tabs-bg-transparent',
  tabBgFilledSelectedVertical: 'blade-tabs-bg-filled-selected-vertical',
  tabStackingContext: 'relative z-[1]',
  tabSelected: 'blade-tabs-selected',
  tabDisabledLink: 'no-underline blade-tabs-disabled-link',
  tabItemText: 'blade-tabs-item-text',
  tabItemTextSelected: 'blade-tabs-item-text-selected',
  tabItemTextMedium: 'text-100 leading-100',
  tabItemTextLarge: 'text-200 leading-200',
  tabItemIcon: 'blade-tabs-item-icon',
  tabItemIconSelected: 'blade-tabs-item-icon-selected',
  tabFilledUnselected: 'blade-tabs-filled-unselected',
  tabFocusRadiusSmall: 'blade-tabs-focus-radius-small',
  tabFocusRadiusMedium: 'blade-tabs-focus-radius-medium',
  tabIndicator: 'absolute pointer-events-none',
  indicatorHorizontalBordered:
    'left-0 top-[-0.5px] h-[2px] bg-interactive-border-neutral-highlighted',
  indicatorVerticalBordered: 'left-[1.75px] top-0 w-[1.5px] bg-interactive-border-neutral-highlighted',
  indicatorFilled: 'left-0 top-0 bg-surface-background-gray-intense',
  indicatorRadiusSmall: 'rounded-small',
  indicatorRadiusMedium: 'rounded-medium',
  indicatorRadiusFilledHorizSmall: 'rounded-xsmall',
  tabPanel: 'outline-none',
  tabPanelHidden: 'hidden',
});
