name: Blade Tokens Upload

on: 
  workflow_dispatch:
    inputs:
      tokens:
        description: 'Token Object'
        required: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  TOKEN_DATA: ${{ github.event.inputs.tokens }}

jobs:
  token-upload:
    name: Upload Tokens
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.5
      - name: Setup Cache & Install Dependencies
        uses: ./.github/actions/install-dependencies
      - name: Upload Tokens
        working-directory: packages/blade
        run: node ./scripts/uploadTokens.js '${{ env.TOKEN_DATA }}'
        env: 
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
