name: Knowledgebase Lint

on: [pull_request]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  validate:
    name: Knowledgebase Lint
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
      - name: Use Node v22
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.1
        with:
          node-version: 22
      - name: Setup Cache & Install Dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build Blade
        run: yarn build
        working-directory: packages/blade
      - name: Run Lint Script
        run: yarn tsc:knowledgebase
