name: Blade Lint Fix

on: [push]

permissions:
  contents: write

jobs:
  lint-fix:
    name: Lint Fix
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Use Node v22
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Setup Cache & Install Dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run Lint Fix
        run: yarn lint:fix:blade
      - name: Commit Lint Fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix: auto lint fix"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
