name: Cancel

on: [push]

jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.0
        with:
          workflow_id: cancel.yml, blade-old-validate.yml, blade-old-release.yml, blade-validate.yml, blade-release.yml, blade-tokens-upload.yml
          access_token: ${{ github.token }}
