name: 'Chromatic'
on: push

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./packages/blade-old
          buildScriptName: web:storybook:build
          token: ${{ secrets.CI_BOT_TOKEN }}
          projectToken: gx0k8mh119
          exitOnceUploaded: true
