name: Quality Checks
on:
  pull_request: {}
  push:
    branches: ["master"]
  schedule:
    - cron: "0 17 * * *"
jobs:
  Code-Analysis:
    uses: razorpay/genesis/.github/workflows/quality-checks.yml@master
    secrets: inherit
