name: Blade Release

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

permissions:
  id-token: write      # For OIDC/npm provenance
  contents: write      # For pushing commits/branches
  pull-requests: write #

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Upgrade npm for OIDC trusted publishing support
        run: npm install -g npm@latest
      - name: Setup Cache & Install Dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build Blade Core
        working-directory: packages/blade-core
        run: yarn build
      - name: Create Release Pull Request & Publish packages
        id: changesets
        uses: changesets/action@v1
        if: github.event_name != 'workflow_dispatch' # only run on master merges
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          BLADE_MCP_SENTRY_DSN: ${{ secrets.BLADE_MCP_SENTRY_DSN }}
          BLADE_SEGMENT_KEY: ${{ secrets.BLADE_SEGMENT_KEY }}
        with:
          publish: yarn release
          commit: 'build: update version'
          title: 'build: update version'
      - name: Publish to public npm registry
        if: steps.changesets.outputs.published == 'true' || github.event_name == 'workflow_dispatch' # run when the package is published via changeset or if a release is triggered manually.
        env:
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          BLADE_MCP_SENTRY_DSN: ${{ secrets.BLADE_MCP_SENTRY_DSN }}
          BLADE_SEGMENT_KEY: ${{ secrets.BLADE_SEGMENT_KEY }}
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
        run: yarn publish-npm
