name: Security Checks
on: pull_request
jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
