name: Security Checks
on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches: ["master"]
jobs:
  semgrep:
    if: (github.actor != 'dependabot[bot]')
    name: Semgrep Scan
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 339
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
