name: Validate

on: [pull_request]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  yarn-lock-changes:
    name: Yarn Lock Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          path: 'yarn.lock'
          token: ${{ secrets.CI_BOT_TOKEN }}

